# Generated by Django 4.0.4 on 2022-05-20 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('DOB', models.DateField(default=datetime.date.today)),
                ('sex', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Illnesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vacxin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inject_times', models.PositiveSmallIntegerField(default=1)),
                ('discription', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField(default=0)),
                ('manufacturer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vacxin_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inject_date', models.DateField(default=datetime.date.today)),
                ('inject_next_time', models.DateField(default=datetime.date(2022, 6, 20))),
                ('vacxin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vacxin')),
                ('vacxin_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
        migrations.CreateModel(
            name='Prevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500)),
                ('illnesses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.illnesses')),
                ('vacxin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vacxin')),
            ],
        ),
    ]
