# Generated by Django 4.0.4 on 2022-05-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacxin',
            old_name='discription',
            new_name='description',
        ),
    ]
