# Generated by Django 4.0.4 on 2022-05-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_discription_vacxin_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacxin_History',
            new_name='VacxinHistory',
        ),
    ]
