# Generated by Django 4.0.4 on 2022-05-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_vacxin_history_vacxinhistory_clientid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacxinhistory',
            old_name='clientID',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='vacxinhistory',
            old_name='vacxinID',
            new_name='vacxin',
        ),
    ]
