# Generated by Django 4.0.4 on 2022-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_clientid_vacxinhistory_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnesses',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
