# Generated by Django 4.0.4 on 2022-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_illnesses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnesses',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='vacxin',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
