# Generated by Django 4.0.4 on 2022-05-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_illnesses_description_alter_vacxin_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnesses',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='illnesses',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
