# Generated by Django 4.0.4 on 2022-05-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_illnesses_prevention_illnesses_vacxin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illnesses',
            name='prevention',
        ),
        migrations.RemoveField(
            model_name='illnesses',
            name='vacxin',
        ),
        migrations.CreateModel(
            name='Prevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500)),
                ('illnesses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.illnesses')),
                ('vacxin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vacxin')),
            ],
        ),
    ]
