# Generated by Django 4.0.4 on 2022-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_illnesses_prevention_remove_illnesses_vacxin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='illnesses',
            name='prevention',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='illnesses',
            name='vacxins',
            field=models.ManyToManyField(to='main.vacxin'),
        ),
        migrations.DeleteModel(
            name='Prevention',
        ),
    ]
