# Generated by Django 4.0.4 on 2022-05-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_illnesses_prevention_illnesses_vacxins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illnesses',
            name='vacxins',
        ),
        migrations.AddField(
            model_name='vacxin',
            name='illnesses',
            field=models.ManyToManyField(to='main.illnesses'),
        ),
    ]
